Search.appendIndex(
    [
                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\ClientAuthConfig",
            "name": "ClientAuthConfig",
            "summary": "Configuration\u0020for\u0020PostgREST\u0020client\u0020authentication.",
            "url": "classes/PostgrestPhp-Client-Base-ClientAuthConfig.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\ClientAuthConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020PostgREST\u0020client\u0020auth\u0020config.",
            "url": "classes/PostgrestPhp-Client-Base-ClientAuthConfig.html#method___construct"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\ClientAuthConfig\u003A\u003A\u0024authSchemaName",
            "name": "authSchemaName",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-ClientAuthConfig.html#property_authSchemaName"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\ClientAuthConfig\u003A\u003A\u0024authFunctionName",
            "name": "authFunctionName",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-ClientAuthConfig.html#property_authFunctionName"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\ClientAuthConfig\u003A\u003A\u0024authArguments",
            "name": "authArguments",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-ClientAuthConfig.html#property_authArguments"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\ClientAuthConfig\u003A\u003A\u0024autoAuth",
            "name": "autoAuth",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-ClientAuthConfig.html#property_autoAuth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\ClientAuthConfig\u003A\u003A\u0024autoAuthGrace",
            "name": "autoAuthGrace",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-ClientAuthConfig.html#property_autoAuthGrace"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient",
            "name": "PostgrestBaseClient",
            "summary": "The\u0020PostgrestBaseClient\u0020holds\u0020all\u0020general\u0020functionality\u0020for\u0020the\u0020PostgREST\u0020client.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020new\u0020PostgREST\u0020client.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method___construct"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003AisAuthenticated\u0028\u0029",
            "name": "isAuthenticated",
            "summary": "Check\u0020whether\u0020the\u0020client\u0020is\u0020authenticated.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method_isAuthenticated"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003AsetAuthToken\u0028\u0029",
            "name": "setAuthToken",
            "summary": "Function\u0020to\u0020manually\u0020set\u0020authentication\u0020token.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method_setAuthToken"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003AgetTokenExpirationTime\u0028\u0029",
            "name": "getTokenExpirationTime",
            "summary": "Returns\u0020the\u0020expiration\u0020time\u0020of\u0020the\u0020authentication\u0020token.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method_getTokenExpirationTime"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003AenableAutoAuth\u0028\u0029",
            "name": "enableAutoAuth",
            "summary": "Enable\u0020auto\u0020authentication\u0020feature.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method_enableAutoAuth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003AdisableAutoAuth\u0028\u0029",
            "name": "disableAutoAuth",
            "summary": "Disable\u0020auto\u0020authentication\u0020feature",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method_disableAutoAuth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "Create\u0020a\u0020new\u0020request\u0020builder\u0020for\u0020a\u0020table\u0020in\u0020a\u0020schema.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method_from"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A_auth\u0028\u0029",
            "name": "_auth",
            "summary": "Authenticate\u0020the\u0020client\u0020using\u0020stored\u0020procedure.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method__auth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A_call\u0028\u0029",
            "name": "_call",
            "summary": "Call\u0020a\u0020stored\u0020procedure.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method__call"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A_run\u0028\u0029",
            "name": "_run",
            "summary": "Run\u0020a\u0020request.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method__run"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A_execute\u0028\u0029",
            "name": "_execute",
            "summary": "Execute\u0020a\u0020request.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method__execute"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003AcreateRequestPromise\u0028\u0029",
            "name": "createRequestPromise",
            "summary": "Sends\u0020the\u0020request\u0020and\u0020optionally\u0020prepends\u0020the\u0020authentication.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#method_createRequestPromise"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024tokenExpirationTime",
            "name": "tokenExpirationTime",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_tokenExpirationTime"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024authHeader",
            "name": "authHeader",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_authHeader"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024authSchemaName",
            "name": "authSchemaName",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_authSchemaName"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024authFunctionName",
            "name": "authFunctionName",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_authFunctionName"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024authArguments",
            "name": "authArguments",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_authArguments"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024autoAuth",
            "name": "autoAuth",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_autoAuth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024currentlyInReAuth",
            "name": "currentlyInReAuth",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_currentlyInReAuth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024autoAuthGrace",
            "name": "autoAuthGrace",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_autoAuthGrace"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024baseUrl",
            "name": "baseUrl",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_baseUrl"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024timeout",
            "name": "timeout",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_timeout"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestBaseClient\u003A\u003A\u0024httpClient",
            "name": "httpClient",
            "summary": "",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestBaseClient.html#property_httpClient"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestClientInterface",
            "name": "PostgrestClientInterface",
            "summary": "Interface\u0020for\u0020both\u0020synchronous\u0020and\u0020asynchronous\u0020PostgREST\u0020clients.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestClientInterface.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestClientInterface\u003A\u003AisAuthenticated\u0028\u0029",
            "name": "isAuthenticated",
            "summary": "Check\u0020whether\u0020the\u0020client\u0020is\u0020authenticated.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestClientInterface.html#method_isAuthenticated"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestClientInterface\u003A\u003AsetAuthToken\u0028\u0029",
            "name": "setAuthToken",
            "summary": "Manually\u0020set\u0020the\u0020authentication\u0020token.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestClientInterface.html#method_setAuthToken"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestClientInterface\u003A\u003AenableAutoAuth\u0028\u0029",
            "name": "enableAutoAuth",
            "summary": "Enable\u0020auto\u0020authentication\u0020feature.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestClientInterface.html#method_enableAutoAuth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestClientInterface\u003A\u003AdisableAutoAuth\u0028\u0029",
            "name": "disableAutoAuth",
            "summary": "Disable\u0020auto\u0020authentication\u0020feature",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestClientInterface.html#method_disableAutoAuth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestClientInterface\u003A\u003Aauth\u0028\u0029",
            "name": "auth",
            "summary": "Authenticate\u0020the\u0020client.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestClientInterface.html#method_auth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestClientInterface\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "Create\u0020a\u0020new\u0020request\u0020builder\u0020for\u0020a\u0020table\u0020in\u0020a\u0020schema.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestClientInterface.html#method_from"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestClientInterface\u003A\u003Acall\u0028\u0029",
            "name": "call",
            "summary": "Call\u0020a\u0020stored\u0020procedure.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestClientInterface.html#method_call"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base\\PostgrestClientInterface\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020a\u0020query.",
            "url": "classes/PostgrestPhp-Client-Base-PostgrestClientInterface.html#method_run"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Exceptions\\FailedAuthException",
            "name": "FailedAuthException",
            "summary": "Exception\u0020thrown\u0020when\u0020the\u0020authentication\u0020failed.",
            "url": "classes/PostgrestPhp-Client-Exceptions-FailedAuthException.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Exceptions\\FailedAuthException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020FailedAuthException.",
            "url": "classes/PostgrestPhp-Client-Exceptions-FailedAuthException.html#method___construct"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Exceptions\\FailedAuthException\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "String\u0020representation\u0020of\u0020the\u0020exception.",
            "url": "classes/PostgrestPhp-Client-Exceptions-FailedAuthException.html#method___toString"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\PostgrestAsyncClient",
            "name": "PostgrestAsyncClient",
            "summary": "PostgrestAsyncClient\u0020is\u0020an\u0020asynchronous\u0020client\u0020for\u0020PostgREST.",
            "url": "classes/PostgrestPhp-Client-PostgrestAsyncClient.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\PostgrestAsyncClient\u003A\u003Aauth\u0028\u0029",
            "name": "auth",
            "summary": "Authenticate\u0020the\u0020client\u0020asynchronously\u0020using\u0020stored\u0020procedure.",
            "url": "classes/PostgrestPhp-Client-PostgrestAsyncClient.html#method_auth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\PostgrestAsyncClient\u003A\u003Acall\u0028\u0029",
            "name": "call",
            "summary": "Call\u0020a\u0020stored\u0020procedure\u0020asynchronously.",
            "url": "classes/PostgrestPhp-Client-PostgrestAsyncClient.html#method_call"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\PostgrestAsyncClient\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020a\u0020request\u0020asynchronously.",
            "url": "classes/PostgrestPhp-Client-PostgrestAsyncClient.html#method_run"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\PostgrestSyncClient",
            "name": "PostgrestSyncClient",
            "summary": "PostgrestSyncClient\u0020is\u0020a\u0020synchronous\u0020client\u0020for\u0020PostgREST.",
            "url": "classes/PostgrestPhp-Client-PostgrestSyncClient.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\PostgrestSyncClient\u003A\u003Aauth\u0028\u0029",
            "name": "auth",
            "summary": "Authenticate\u0020the\u0020client\u0020synchronously\u0020using\u0020stored\u0020procedure",
            "url": "classes/PostgrestPhp-Client-PostgrestSyncClient.html#method_auth"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\PostgrestSyncClient\u003A\u003Acall\u0028\u0029",
            "name": "call",
            "summary": "Call\u0020a\u0020stored\u0020procedure\u0020synchronously.",
            "url": "classes/PostgrestPhp-Client-PostgrestSyncClient.html#method_call"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\PostgrestSyncClient\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020a\u0020request\u0020synchronously.",
            "url": "classes/PostgrestPhp-Client-PostgrestSyncClient.html#method_run"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\CountType",
            "name": "CountType",
            "summary": "Enum\u0020for\u0020the\u0020type\u0020of\u0020counts\u0020PostgREST\u0020supports.",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-CountType.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\CountType\u003A\u003AEXACT",
            "name": "EXACT",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-CountType.html#enumcase_EXACT"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\CountType\u003A\u003APLANNED",
            "name": "PLANNED",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-CountType.html#enumcase_PLANNED"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\CountType\u003A\u003AESTIMATED",
            "name": "ESTIMATED",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-CountType.html#enumcase_ESTIMATED"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\DataFormat",
            "name": "DataFormat",
            "summary": "Enum\u0020for\u0020the\u0020data\u0020format\u0020PostgREST\u0020supports\u0020for\u0020transmitting\u0020data.",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-DataFormat.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\DataFormat\u003A\u003AJSON",
            "name": "JSON",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-DataFormat.html#enumcase_JSON"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\DataFormat\u003A\u003ACSV",
            "name": "CSV",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-DataFormat.html#enumcase_CSV"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\DuplicateResolution",
            "name": "DuplicateResolution",
            "summary": "Enum\u0020for\u0020the\u0020duplicate\u0020resolution\u0020strategies\u0020PostgREST\u0020supports.",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-DuplicateResolution.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\DuplicateResolution\u003A\u003ANONE",
            "name": "NONE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-DuplicateResolution.html#enumcase_NONE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\DuplicateResolution\u003A\u003AIGNORE",
            "name": "IGNORE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-DuplicateResolution.html#enumcase_IGNORE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\DuplicateResolution\u003A\u003AMERGE",
            "name": "MERGE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-DuplicateResolution.html#enumcase_MERGE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\IsCheck",
            "name": "IsCheck",
            "summary": "Enum\u0020for\u0020the\u0020is\u0020check\u0020types\u0020PostgREST\u0020supports.",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-IsCheck.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\IsCheck\u003A\u003ANULL",
            "name": "NULL",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-IsCheck.html#enumcase_NULL"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\IsCheck\u003A\u003ATRUE",
            "name": "TRUE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-IsCheck.html#enumcase_TRUE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\IsCheck\u003A\u003AFALSE",
            "name": "FALSE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-IsCheck.html#enumcase_FALSE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\IsCheck\u003A\u003AUNKNOWN",
            "name": "UNKNOWN",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-IsCheck.html#enumcase_UNKNOWN"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator",
            "name": "Operator",
            "summary": "Enum\u0020for\u0020the\u0020operators\u0020PostgREST\u0020supports.",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AEQUAL",
            "name": "EQUAL",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_EQUAL"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AGREATER_THAN",
            "name": "GREATER_THAN",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_GREATER_THAN"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AGREATER_THAN_OR_EQUAL",
            "name": "GREATER_THAN_OR_EQUAL",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_GREATER_THAN_OR_EQUAL"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ALESS_THAN",
            "name": "LESS_THAN",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_LESS_THAN"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ALESS_THAN_OR_EQUAL",
            "name": "LESS_THAN_OR_EQUAL",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_LESS_THAN_OR_EQUAL"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ANOT_EQUAL",
            "name": "NOT_EQUAL",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_NOT_EQUAL"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ALIKE",
            "name": "LIKE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_LIKE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AILIKE",
            "name": "ILIKE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_ILIKE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AMATCH",
            "name": "MATCH",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_MATCH"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AIMATCH",
            "name": "IMATCH",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_IMATCH"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AIN",
            "name": "IN",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_IN"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AIS",
            "name": "IS",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_IS"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AIS_DISTINCT_FROM",
            "name": "IS_DISTINCT_FROM",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_IS_DISTINCT_FROM"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AFULL_TEXT_SEARCH",
            "name": "FULL_TEXT_SEARCH",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_FULL_TEXT_SEARCH"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003APLAIN_FULL_TEXT_SEARCH",
            "name": "PLAIN_FULL_TEXT_SEARCH",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_PLAIN_FULL_TEXT_SEARCH"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003APHRASE_FULL_TEXT_SEARCH",
            "name": "PHRASE_FULL_TEXT_SEARCH",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_PHRASE_FULL_TEXT_SEARCH"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AWEBSEARCH_FULL_TEXT_SEARCH",
            "name": "WEBSEARCH_FULL_TEXT_SEARCH",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_WEBSEARCH_FULL_TEXT_SEARCH"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ACONTAINS",
            "name": "CONTAINS",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_CONTAINS"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ACONTAINED_IN",
            "name": "CONTAINED_IN",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_CONTAINED_IN"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AOVERLAP",
            "name": "OVERLAP",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_OVERLAP"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ASTRICTLY_LEFT_OF",
            "name": "STRICTLY_LEFT_OF",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_STRICTLY_LEFT_OF"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ASTRICTLY_RIGHT_OF",
            "name": "STRICTLY_RIGHT_OF",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_STRICTLY_RIGHT_OF"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ANOT_EXTEND_TO_RIGHT",
            "name": "NOT_EXTEND_TO_RIGHT",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_NOT_EXTEND_TO_RIGHT"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ANOT_EXTEND_TO_LEFT",
            "name": "NOT_EXTEND_TO_LEFT",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_NOT_EXTEND_TO_LEFT"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AADJACENT",
            "name": "ADJACENT",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_ADJACENT"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003ANOT",
            "name": "NOT",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_NOT"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AOR",
            "name": "OR",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_OR"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AAND",
            "name": "AND",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_AND"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AALL",
            "name": "ALL",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_ALL"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\Operator\u003A\u003AANY",
            "name": "ANY",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-Operator.html#enumcase_ANY"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OrderDirection",
            "name": "OrderDirection",
            "summary": "Enum\u0020for\u0020the\u0020order\u0020directions\u0020PostgREST\u0020supports.",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OrderDirection.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OrderDirection\u003A\u003AASC",
            "name": "ASC",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OrderDirection.html#enumcase_ASC"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OrderDirection\u003A\u003ADESC",
            "name": "DESC",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OrderDirection.html#enumcase_DESC"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OrderNulls",
            "name": "OrderNulls",
            "summary": "Enum\u0020for\u0020the\u0020null\u0020order\u0020types\u0020PostgREST\u0020supports.",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OrderNulls.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OrderNulls\u003A\u003ANONE",
            "name": "NONE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OrderNulls.html#enumcase_NONE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OrderNulls\u003A\u003ANULLS_FIRST",
            "name": "NULLS_FIRST",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OrderNulls.html#enumcase_NULLS_FIRST"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OrderNulls\u003A\u003ANULLS_LAST",
            "name": "NULLS_LAST",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OrderNulls.html#enumcase_NULLS_LAST"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OverlapType",
            "name": "OverlapType",
            "summary": "Enum\u0020for\u0020the\u0020overlap\u0020types\u0020PostgREST\u0020supports.",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OverlapType.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OverlapType\u003A\u003AARRAY",
            "name": "ARRAY",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OverlapType.html#enumcase_ARRAY"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OverlapType\u003A\u003ARANGE_ALL_EXCLUSIVE",
            "name": "RANGE_ALL_EXCLUSIVE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OverlapType.html#enumcase_RANGE_ALL_EXCLUSIVE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OverlapType\u003A\u003ARANGE_LOWER_EXCLUSIVE",
            "name": "RANGE_LOWER_EXCLUSIVE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OverlapType.html#enumcase_RANGE_LOWER_EXCLUSIVE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OverlapType\u003A\u003ARANGE_UPPER_EXCLUSIVE",
            "name": "RANGE_UPPER_EXCLUSIVE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OverlapType.html#enumcase_RANGE_UPPER_EXCLUSIVE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\OverlapType\u003A\u003ARANGE_ALL_INCLUSIVE",
            "name": "RANGE_ALL_INCLUSIVE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-OverlapType.html#enumcase_RANGE_ALL_INCLUSIVE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\ReturnFormat",
            "name": "ReturnFormat",
            "summary": "Enum\u0020for\u0020the\u0020return\u0020formats\u0020PostgREST\u0020supports.",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-ReturnFormat.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\ReturnFormat\u003A\u003ANONE",
            "name": "NONE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-ReturnFormat.html#enumcase_NONE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\ReturnFormat\u003A\u003AHEADERS_ONLY",
            "name": "HEADERS_ONLY",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-ReturnFormat.html#enumcase_HEADERS_ONLY"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums\\ReturnFormat\u003A\u003AREPRESENTATION",
            "name": "REPRESENTATION",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Enums-ReturnFormat.html#enumcase_REPRESENTATION"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\DataEncodingException",
            "name": "DataEncodingException",
            "summary": "Exception\u0020thrown\u0020when\u0020data\u0020can\u0020not\u0020be\u0020converted\u0020to\u0020a\u0020specified\u0020format.",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-DataEncodingException.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\DataEncodingException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020DataEncodingException.",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-DataEncodingException.html#method___construct"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\DataEncodingException\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "String\u0020representation\u0020of\u0020the\u0020exception.",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-DataEncodingException.html#method___toString"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\DataEncodingException\u003A\u003AJSON_ENCODING_FAILED",
            "name": "JSON_ENCODING_FAILED",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-DataEncodingException.html#constant_JSON_ENCODING_FAILED"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\FilterLogicException",
            "name": "FilterLogicException",
            "summary": "Exception\u0020thrown\u0020when\u0020the\u0020filter\u0020logic\u0020is\u0020invalid.",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-FilterLogicException.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\FilterLogicException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020FilterLogicException.",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-FilterLogicException.html#method___construct"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\FilterLogicException\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "String\u0020representation\u0020of\u0020the\u0020exception.",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-FilterLogicException.html#method___toString"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\FilterLogicException\u003A\u003AMISSING_MODIFIER",
            "name": "MISSING_MODIFIER",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-FilterLogicException.html#constant_MISSING_MODIFIER"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\FilterLogicException\u003A\u003ABOTH_MODIFIERS_ACTIVE",
            "name": "BOTH_MODIFIERS_ACTIVE",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-FilterLogicException.html#constant_BOTH_MODIFIERS_ACTIVE"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\FilterLogicException\u003A\u003ADUPLICATE_RESOLUTION_REQUIRED",
            "name": "DUPLICATE_RESOLUTION_REQUIRED",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-FilterLogicException.html#constant_DUPLICATE_RESOLUTION_REQUIRED"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\NotUnifiedValuesException",
            "name": "NotUnifiedValuesException",
            "summary": "Exception\u0020thrown\u0020when\u0020not\u0020all\u0020values\u0020are\u0020unified.",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-NotUnifiedValuesException.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\NotUnifiedValuesException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020NotUnifiedValuesException.",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-NotUnifiedValuesException.html#method___construct"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\NotUnifiedValuesException\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "String\u0020representation\u0020of\u0020the\u0020exception.",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-NotUnifiedValuesException.html#method___toString"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\NotUnifiedValuesException\u003A\u003ANOT_UNIFIED_ARRAY",
            "name": "NOT_UNIFIED_ARRAY",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-NotUnifiedValuesException.html#constant_NOT_UNIFIED_ARRAY"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions\\NotUnifiedValuesException\u003A\u003ANOT_UNIFIED_START_END",
            "name": "NOT_UNIFIED_START_END",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Exceptions-NotUnifiedValuesException.html#constant_NOT_UNIFIED_START_END"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Helper",
            "name": "Helper",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Helper.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Helper\u003A\u003AcontainsAny\u0028\u0029",
            "name": "containsAny",
            "summary": "Check\u0020if\u0020string\u0020contains\u0020any\u0020of\u0020the\u0020needles.",
            "url": "classes/PostgrestPhp-RequestBuilder-Helper.html#method_containsAny"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Helper\u003A\u003AescapeString\u0028\u0029",
            "name": "escapeString",
            "summary": "Escape\u0020the\u0020given\u0020value\u0020to\u0020comply\u0020with\u0020the\u0020PostgREST\u0020API.",
            "url": "classes/PostgrestPhp-RequestBuilder-Helper.html#method_escapeString"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Helper\u003A\u003AimplodeWithBraces\u0028\u0029",
            "name": "implodeWithBraces",
            "summary": "Escape\u0020each\u0020element\u0020in\u0020the\u0020given\u0020array\u0020and\u0020implode\u0020them\u0020with\u0020the\u0020given\u0020open\u0020and\u0020close\u0020strings.",
            "url": "classes/PostgrestPhp-RequestBuilder-Helper.html#method_implodeWithBraces"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Helper\u003A\u003AcheckUnifiedValueTypes\u0028\u0029",
            "name": "checkUnifiedValueTypes",
            "summary": "Check\u0020if\u0020all\u0020values\u0020in\u0020the\u0020given\u0020array\u0020are\u0020of\u0020the\u0020same\u0020type.",
            "url": "classes/PostgrestPhp-RequestBuilder-Helper.html#method_checkUnifiedValueTypes"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Helper\u003A\u003AconvertToCSV\u0028\u0029",
            "name": "convertToCSV",
            "summary": "Convert\u0020the\u0020given\u0020data\u0020to\u0020CSV.",
            "url": "classes/PostgrestPhp-RequestBuilder-Helper.html#method_convertToCSV"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\OrderColumn",
            "name": "OrderColumn",
            "summary": "A\u0020column\u0020to\u0020order\u0020by.",
            "url": "classes/PostgrestPhp-RequestBuilder-OrderColumn.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\OrderColumn\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020order\u0020column.",
            "url": "classes/PostgrestPhp-RequestBuilder-OrderColumn.html#method___construct"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\OrderColumn\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-OrderColumn.html#property_name"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\OrderColumn\u003A\u003A\u0024direction",
            "name": "direction",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-OrderColumn.html#property_direction"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\OrderColumn\u003A\u003A\u0024orderNulls",
            "name": "orderNulls",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-OrderColumn.html#property_orderNulls"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder",
            "name": "PostgrestRequestBuilder",
            "summary": "PostgREST\u0020request\u0020builder.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020PostgREST\u0020request\u0020builder.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method___construct"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "Get\u0020header\u0020value\u0020by\u0020name.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_getHeader"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003AsetHeader\u0028\u0029",
            "name": "setHeader",
            "summary": "Set\u0020specific\u0020header.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_setHeader"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003Aselect\u0028\u0029",
            "name": "select",
            "summary": "Set\u0020the\u0020columns\u0020to\u0020select\u0020from\u0020the\u0020table.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_select"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "Insert\u0020data\u0020into\u0020the\u0020table.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_insert"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003Aupsert\u0028\u0029",
            "name": "upsert",
            "summary": "Insert\u0020data\u0020into\u0020the\u0020table,\u0020or\u0020resolve\u0020conflict\u0020if\u0020rows\u0020already\u0020exists.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_upsert"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020table.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_update"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020from\u0020the\u0020table.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_delete"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003AorderBy\u0028\u0029",
            "name": "orderBy",
            "summary": "Order\u0020results\u0020by\u0020the\u0020given\u0020columns.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_orderBy"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003Alimit\u0028\u0029",
            "name": "limit",
            "summary": "Set\u0020the\u0020limit\u0020for\u0020the\u0020results.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_limit"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003Aoffset\u0028\u0029",
            "name": "offset",
            "summary": "Set\u0020the\u0020offset\u0020for\u0020the\u0020results.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_offset"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "Count\u0020the\u0020result\u0020range.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_count"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003AgetRequestData\u0028\u0029",
            "name": "getRequestData",
            "summary": "Get\u0020data\u0020from\u0020class\u0020which\u0020is\u0020needed\u0020to\u0020run\u0020the\u0020request",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_getRequestData"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003A_insert\u0028\u0029",
            "name": "_insert",
            "summary": "Underlying\u0020function\u0020which\u0020backs\u0020insert\u0028\u0029\u0020and\u0020upsert\u0028\u0029.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method__insert"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003AencodeData\u0028\u0029",
            "name": "encodeData",
            "summary": "Encode\u0020the\u0020given\u0020data\u0020in\u0020the\u0020given\u0020format.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_encodeData"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003AsetMissingAsDefault\u0028\u0029",
            "name": "setMissingAsDefault",
            "summary": "Set\u0020the\u0020missing\u0020columns\u0020to\u0020their\u0020default\u0020values.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_setMissingAsDefault"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003AsetReturnFormat\u0028\u0029",
            "name": "setReturnFormat",
            "summary": "Set\u0020the\u0020return\u0020format.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_setReturnFormat"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003AsetDuplicateResolution\u0028\u0029",
            "name": "setDuplicateResolution",
            "summary": "Set\u0020the\u0020duplicate\u0020resolution.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_setDuplicateResolution"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003AappendPreferHeader\u0028\u0029",
            "name": "appendPreferHeader",
            "summary": "Append\u0020the\u0020Prefer\u0020header.",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#method_appendPreferHeader"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003A\u0024filters",
            "name": "filters",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#property_filters"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003A\u0024method",
            "name": "method",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#property_method"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#property_headers"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#property_body"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003A\u0024helper",
            "name": "helper",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#property_helper"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003A\u0024schemaName",
            "name": "schemaName",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#property_schemaName"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\PostgrestRequestBuilder\u003A\u003A\u0024tableName",
            "name": "tableName",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-PostgrestRequestBuilder.html#property_tableName"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators",
            "name": "ArrayRangeOperators",
            "summary": "Trait\u0020to\u0020represent\u0020array\u0020range\u0020operators.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators\u003A\u003Acs\u0028\u0029",
            "name": "cs",
            "summary": "Contains\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html#method_cs"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators\u003A\u003Acd\u0028\u0029",
            "name": "cd",
            "summary": "Contained\u0020in\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html#method_cd"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators\u003A\u003Aov\u0028\u0029",
            "name": "ov",
            "summary": "Overlap\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html#method_ov"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators\u003A\u003Asl\u0028\u0029",
            "name": "sl",
            "summary": "Strictly\u0020left\u0020of\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html#method_sl"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators\u003A\u003Asr\u0028\u0029",
            "name": "sr",
            "summary": "Strictly\u0020right\u0020of\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html#method_sr"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators\u003A\u003Anxr\u0028\u0029",
            "name": "nxr",
            "summary": "Not\u0020extend\u0020to\u0020right\u0020of\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html#method_nxr"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators\u003A\u003Anxl\u0028\u0029",
            "name": "nxl",
            "summary": "Not\u0020extend\u0020to\u0020left\u0020of\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html#method_nxl"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators\u003A\u003Aadj\u0028\u0029",
            "name": "adj",
            "summary": "Adjacent\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html#method_adj"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators\u003A\u003AarrayHelper\u0028\u0029",
            "name": "arrayHelper",
            "summary": "Array\u0020operator\u0020helper.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html#method_arrayHelper"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ArrayRangeOperators\u003A\u003ArangeHelper\u0028\u0029",
            "name": "rangeHelper",
            "summary": "Range\u0020operator\u0020helper.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ArrayRangeOperators.html#method_rangeHelper"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\EqualityOperators",
            "name": "EqualityOperators",
            "summary": "Trait\u0020to\u0020represent\u0020equality\u0020operators.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-EqualityOperators.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\EqualityOperators\u003A\u003Aeq\u0028\u0029",
            "name": "eq",
            "summary": "Equals\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-EqualityOperators.html#method_eq"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\EqualityOperators\u003A\u003Aneq\u0028\u0029",
            "name": "neq",
            "summary": "Not\u0020equal\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-EqualityOperators.html#method_neq"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\EqualityOperators\u003A\u003Ais\u0028\u0029",
            "name": "is",
            "summary": "Is\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-EqualityOperators.html#method_is"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\EqualityOperators\u003A\u003Ain\u0028\u0029",
            "name": "in",
            "summary": "In\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-EqualityOperators.html#method_in"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\EqualityOperators\u003A\u003Aisdistinct\u0028\u0029",
            "name": "isdistinct",
            "summary": "Is\u0020distinct\u0020from\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-EqualityOperators.html#method_isdistinct"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\FilterOperators",
            "name": "FilterOperators",
            "summary": "Trait\u0020to\u0020represent\u0020filter\u0020helpers.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-FilterOperators.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\FilterOperators\u003A\u003AfilterRawColumn\u0028\u0029",
            "name": "filterRawColumn",
            "summary": "Raw\u0020filter\u0020function\u0020for\u0020columns.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-FilterOperators.html#method_filterRawColumn"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\FilterOperators\u003A\u003AfilterRaw\u0028\u0029",
            "name": "filterRaw",
            "summary": "Raw\u0020filter\u0020function\u0020for\u0020tables.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-FilterOperators.html#method_filterRaw"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\FullTextSearchOperators",
            "name": "FullTextSearchOperators",
            "summary": "Trait\u0020to\u0020represent\u0020full\u0020text\u0020search\u0020operators.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-FullTextSearchOperators.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\FullTextSearchOperators\u003A\u003Afts\u0028\u0029",
            "name": "fts",
            "summary": "Full\u0020text\u0020search\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-FullTextSearchOperators.html#method_fts"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\FullTextSearchOperators\u003A\u003Aplfts\u0028\u0029",
            "name": "plfts",
            "summary": "Plain\u0020full\u0020text\u0020search\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-FullTextSearchOperators.html#method_plfts"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\FullTextSearchOperators\u003A\u003Aphfts\u0028\u0029",
            "name": "phfts",
            "summary": "Phrase\u0020full\u0020text\u0020search\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-FullTextSearchOperators.html#method_phfts"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\FullTextSearchOperators\u003A\u003Awfts\u0028\u0029",
            "name": "wfts",
            "summary": "Websearch\u0020full\u0020text\u0020search\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-FullTextSearchOperators.html#method_wfts"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\FullTextSearchOperators\u003A\u003AftsHelper\u0028\u0029",
            "name": "ftsHelper",
            "summary": "Full\u0020text\u0020search\u0020operator\u0020helper.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-FullTextSearchOperators.html#method_ftsHelper"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\GreaterLessOperators",
            "name": "GreaterLessOperators",
            "summary": "Trait\u0020to\u0020represent\u0020greater\/less\u0020operators.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-GreaterLessOperators.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\GreaterLessOperators\u003A\u003Agt\u0028\u0029",
            "name": "gt",
            "summary": "Greater\u0020than\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-GreaterLessOperators.html#method_gt"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\GreaterLessOperators\u003A\u003Agte\u0028\u0029",
            "name": "gte",
            "summary": "Greater\u0020than\u0020or\u0020equal\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-GreaterLessOperators.html#method_gte"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\GreaterLessOperators\u003A\u003Alt\u0028\u0029",
            "name": "lt",
            "summary": "Less\u0020than\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-GreaterLessOperators.html#method_lt"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\GreaterLessOperators\u003A\u003Alte\u0028\u0029",
            "name": "lte",
            "summary": "Less\u0020than\u0020or\u0020equal\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-GreaterLessOperators.html#method_lte"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\GreaterLessOperators\u003A\u003AgreaterLessHelper\u0028\u0029",
            "name": "greaterLessHelper",
            "summary": "Greater\u0020than\u0020operator\u0020helper.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-GreaterLessOperators.html#method_greaterLessHelper"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators",
            "name": "ModifierOperators",
            "summary": "Trait\u0020to\u0020represent\u0020logic\u0020modifier\u0020operators.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003Anot\u0028\u0029",
            "name": "not",
            "summary": "Negate\u0020next\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#method_not"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "Enable\u0020\u0027all\u0027\u0020modifier\u0020for\u0020next\u0020operator\u0020\u0028which\u0020supports\u0020it\u0029.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#method_all"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003Aany\u0028\u0029",
            "name": "any",
            "summary": "Enable\u0020\u0027any\u0027\u0020modifier\u0020for\u0020next\u0020operator\u0020\u0028which\u0020supports\u0020it\u0029.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#method_any"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003AnegateOperator\u0028\u0029",
            "name": "negateOperator",
            "summary": "Prepend\u0020negation\u0020to\u0020operator\u0020if\u0020necessary.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#method_negateOperator"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003AallOperator\u0028\u0029",
            "name": "allOperator",
            "summary": "Prepend\u0020\u0027all\u0027\u0020modifier\u0020to\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#method_allOperator"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003AanyOperator\u0028\u0029",
            "name": "anyOperator",
            "summary": "Prepend\u0020\u0027any\u0027\u0020modifier\u0020to\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#method_anyOperator"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003AcheckOperatorModifier\u0028\u0029",
            "name": "checkOperatorModifier",
            "summary": "Check\u0020whether\u0020all\u0020values\u0020in\u0020an\u0020array\u0020are\u0020of\u0020same\u0020type\u0020and\u0020check\u0020whether\u0020a\u0020modifier\u0020is\u0020active.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#method_checkOperatorModifier"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003AapplyOperatorModifier\u0028\u0029",
            "name": "applyOperatorModifier",
            "summary": "Apply\u0020active\u0020modifier\u0020to\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#method_applyOperatorModifier"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003A\u0024negateNextFilter",
            "name": "negateNextFilter",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#property_negateNextFilter"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003A\u0024allNextFilter",
            "name": "allNextFilter",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#property_allNextFilter"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\ModifierOperators\u003A\u003A\u0024anyNextFilter",
            "name": "anyNextFilter",
            "summary": "",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-ModifierOperators.html#property_anyNextFilter"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\PatternMatchingOperators",
            "name": "PatternMatchingOperators",
            "summary": "Trait\u0020to\u0020represent\u0020pattern\u0020matching\u0020operators.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-PatternMatchingOperators.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\PatternMatchingOperators\u003A\u003Alike\u0028\u0029",
            "name": "like",
            "summary": "Like\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-PatternMatchingOperators.html#method_like"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\PatternMatchingOperators\u003A\u003Ailike\u0028\u0029",
            "name": "ilike",
            "summary": "ILike\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-PatternMatchingOperators.html#method_ilike"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\PatternMatchingOperators\u003A\u003Amatch\u0028\u0029",
            "name": "match",
            "summary": "Match\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-PatternMatchingOperators.html#method_match"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\PatternMatchingOperators\u003A\u003Aimatch\u0028\u0029",
            "name": "imatch",
            "summary": "IMatch\u0020operator.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-PatternMatchingOperators.html#method_imatch"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits\\PatternMatchingOperators\u003A\u003ApatternMatchingHelper\u0028\u0029",
            "name": "patternMatchingHelper",
            "summary": "Pattern\u0020matching\u0020operator\u0020helper.",
            "url": "classes/PostgrestPhp-RequestBuilder-Traits-PatternMatchingOperators.html#method_patternMatchingHelper"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException",
            "name": "PostgrestErrorException",
            "summary": "Exception\u0020which\u0020parses\u0020and\u0020wraps\u0020a\u0020Throwable.",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020PostgrestErrorException.",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#method___construct"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "String\u0020representation\u0020of\u0020the\u0020exception.",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#method___toString"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003AgetStatusCode\u0028\u0029",
            "name": "getStatusCode",
            "summary": "Get\u0020the\u0020response\u0020status\u0020code.",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#method_getStatusCode"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003AgetReasonPhrase\u0028\u0029",
            "name": "getReasonPhrase",
            "summary": "Get\u0020the\u0020response\u0020reason\u0020phrase.",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#method_getReasonPhrase"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003AgetResponseBody\u0028\u0029",
            "name": "getResponseBody",
            "summary": "Get\u0020the\u0020unparsed\u0020response\u0020body.",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#method_getResponseBody"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003AgetPostgrestErrorCode\u0028\u0029",
            "name": "getPostgrestErrorCode",
            "summary": "Get\u0020the\u0020Postgrest\u0020error\u0020code.",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#method_getPostgrestErrorCode"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003AgetPostgrestErrorMessage\u0028\u0029",
            "name": "getPostgrestErrorMessage",
            "summary": "Get\u0020the\u0020Postgrest\u0020error\u0020message.",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#method_getPostgrestErrorMessage"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003A\u0024statusCode",
            "name": "statusCode",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#property_statusCode"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003A\u0024reasonPhrase",
            "name": "reasonPhrase",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#property_reasonPhrase"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003A\u0024responseBody",
            "name": "responseBody",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#property_responseBody"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003A\u0024postgrestErrorCode",
            "name": "postgrestErrorCode",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#property_postgrestErrorCode"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions\\PostgrestErrorException\u003A\u003A\u0024postgrestErrorMessage",
            "name": "postgrestErrorMessage",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-Exceptions-PostgrestErrorException.html#property_postgrestErrorMessage"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse",
            "name": "PostgrestResponse",
            "summary": "PostgrestResponse\u0020holds\u0020the\u0020response\u0020from\u0020the\u0020PostgREST\u0020server.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020PostgrestResponse.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method___construct"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003AgetLocation\u0028\u0029",
            "name": "getLocation",
            "summary": "Get\u0020the\u0020location\u0020for\u0020the\u0020column\u0020using\u0020Location\u0020header\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_getLocation"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003AgetRangeStart\u0028\u0029",
            "name": "getRangeStart",
            "summary": "Get\u0020the\u0020start\u0020of\u0020the\u0020range\u0020using\u0020Content\u002DRange\u0020header\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_getRangeStart"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003AgetRangeEnd\u0028\u0029",
            "name": "getRangeEnd",
            "summary": "Get\u0020the\u0020end\u0020of\u0020the\u0020range\u0020using\u0020Content\u002DRange\u0020header\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_getRangeEnd"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003AgetRangeTotal\u0028\u0029",
            "name": "getRangeTotal",
            "summary": "Get\u0020the\u0020total\u0020of\u0020the\u0020range\u0020using\u0020Content\u002DRange\u0020header\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_getRangeTotal"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003AgetStatusCode\u0028\u0029",
            "name": "getStatusCode",
            "summary": "Get\u0020the\u0020status\u0020code\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_getStatusCode"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003ArawResult\u0028\u0029",
            "name": "rawResult",
            "summary": "Get\u0020the\u0020raw\u0020result\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_rawResult"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003AgetHeaders\u0028\u0029",
            "name": "getHeaders",
            "summary": "Get\u0020the\u0020headers\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_getHeaders"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003Aresult\u0028\u0029",
            "name": "result",
            "summary": "Get\u0020the\u0020parsed\u0020body\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_result"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003AparseLocationHeader\u0028\u0029",
            "name": "parseLocationHeader",
            "summary": "Parse\u0020the\u0020Location\u0020header\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_parseLocationHeader"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003AparseContentRangeHeader\u0028\u0029",
            "name": "parseContentRangeHeader",
            "summary": "Parse\u0020the\u0020Content\u002DRange\u0020header\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_parseContentRangeHeader"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003AparseRange\u0028\u0029",
            "name": "parseRange",
            "summary": "Parse\u0020the\u0020range\u0020of\u0020the\u0020Content\u002DRange\u0020header\u0020of\u0020the\u0020response.",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#method_parseRange"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#property_body"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003A\u0024statusCode",
            "name": "statusCode",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#property_statusCode"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#property_headers"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003A\u0024parsedBody",
            "name": "parsedBody",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#property_parsedBody"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003A\u0024location",
            "name": "location",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#property_location"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003A\u0024contentRangeStart",
            "name": "contentRangeStart",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#property_contentRangeStart"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003A\u0024contentRangeEnd",
            "name": "contentRangeEnd",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#property_contentRangeEnd"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003A\u0024contentRangeTotal",
            "name": "contentRangeTotal",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#property_contentRangeTotal"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\PostgrestResponse\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/PostgrestPhp-Response-PostgrestResponse.html#property_response"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Base",
            "name": "Base",
            "summary": "",
            "url": "namespaces/postgrestphp-client-base.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Client\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/postgrestphp-client-exceptions.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Client",
            "name": "Client",
            "summary": "",
            "url": "namespaces/postgrestphp-client.html"
        },                {
            "fqsen": "\\PostgrestPhp",
            "name": "PostgrestPhp",
            "summary": "",
            "url": "namespaces/postgrestphp.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Enums",
            "name": "Enums",
            "summary": "",
            "url": "namespaces/postgrestphp-requestbuilder-enums.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/postgrestphp-requestbuilder-exceptions.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder",
            "name": "RequestBuilder",
            "summary": "",
            "url": "namespaces/postgrestphp-requestbuilder.html"
        },                {
            "fqsen": "\\PostgrestPhp\\RequestBuilder\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/postgrestphp-requestbuilder-traits.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Response\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/postgrestphp-response-exceptions.html"
        },                {
            "fqsen": "\\PostgrestPhp\\Response",
            "name": "Response",
            "summary": "",
            "url": "namespaces/postgrestphp-response.html"
        }            ]
);
