name: Lint and test

on:
  pull_request:
    branches:
      - master
    paths:
      - "src/**.php"
      - "tests/**.php"
  workflow_dispatch:

jobs:
  lint:
    name: Run linters and analyzers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install project dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
      - name: PHPStan Static Analysis
        run: vendor/bin/phpstan analyze
      - name: PHP Mess Detector Analysis
        run: vendor/bin/phpmd src/ github ruleset.xml
      - name: Code style check
        run: vendor/bin/ecs check --no-progress-bar --clear-cache --no-interaction

  test:
    name: Test with all versions
    needs: [lint]
    strategy:
      matrix:
        # Uncomment as soon as we can run Linux container on Windows
        # ref: https://github.com/actions/runner-images/issues/1143
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        php: ["8.1", "8.2"]
        postgresql: ["12", "13", "14", "15"]
        postgrest: ["9", "10", "11"]
        exclude:
          - postgresql: "15"
            postgrest: "9"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ matrix.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ matrix.os }}-buildx-
      - name: Start up services
        run: docker-compose up -d postgresql${{ matrix.postgresql }} postgrest${{ matrix.postgrest }}
      - name: Install project dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          dev: yes
      - name: Run all test cases
        run: vendor/bin/phpunit tests
        env:
          POSTGREST_VERSION: ${{ matrix.postgrest }}
        # uses: php-actions/phpunit@v3
        # with:
        #   configuration: ./phpunit.xml
