name: Update Packagist

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "**"
  release:

jobs:
  packagist:
    name: Notify Packagist about new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Packagist
        uses: mnavarrocarter/packagist-update@v1.0.0
        with:
          username: "campoint"
          api_token: ${{ secrets.PACKAGIST_TOKEN }}
